### PR TITLE
Save and restore last target when accessing the page again

### PR DESCRIPTION
**Pull request by s-rigaud**
Hi 👋 
First of all, thanks ! Your project saved me a lot of hours for personal projects 😄 

I think it might be a good feature to keep the target saved between two access to the page. For example, I mainly use your website to generate Pydantic models and I don't care about the others. It would be nice to have it set to Pydantic each time 😃 

I just updated the tsx file, you still need to build the project and to publish it. I hope you will implement this feature soon !

### CODE REVIEW

**Comment by Gowee** [comment]
Hi, s-rigaud. 

To make the target in the URL hash still relevant, I tweak the code slightly: https://github.com/Gowee/json2pyi/commit/caf78fa2869c33655fd1900fae8162ae0578fee0

These should allow restoring the target from the URL hash in addition to localStorage. I have tested on Chrome/Firefox, to find the URL without hash always takes higher priority in the address bar. So they should work like a charm without interfering with each other. In case there is still any issue around this in other cases, please let me know.

Thanks for your contribution!

**Comment by Gowee** [comment]
The new build of Web app appears to be blocked by https://github.com/rustwasm/wasm-pack/issues/1248. Hopefully to be resolved soon.

**Comment by s-rigaud** [comment]
Can't you downgrade to a previous version to build the website ?

**Comment by Gowee** [comment]
It is an external dep that is out of the control of the lock file. I just tweaked the build script on pages.dev as a temporary fix. Now the new build has been deployed: https://github.com/Gowee/json2pyi/runs/12218782428.

**Pull request merged**
